Repository quan0715/grouping_application, pull requests merged in 2023-12, with the labels that each got.

#63 fix: fix the migrations of database
  grouping_server/database/migrations/0001_initial.py
  grouping_server/database/migrations/0002_activity_image_workspace_user_introduction_and_more.py
  grouping_server/database/migrations/0002_rename_childs_activity_children_and_more.py
  grouping_server/database/models.py
Labels: bug, back-end

#66 Feats: add the setting frame with account logout button
  .gitignore
  grouping_flutter/lib/app/presentation/providers/token_manager.dart
  grouping_flutter/lib/app/presentation/views/routes.dart
  grouping_flutter/lib/auth/data/datasources/auth_local_data_source.dart
  grouping_flutter/lib/auth/data/datasources/auth_remote_data_source.dart
  grouping_flutter/lib/auth/data/models/auth_token_model.dart
  grouping_flutter/lib/auth/data/repositories/auth_repository_impl.dart
  grouping_flutter/lib/auth/domain/usecases/logout_usecase.dart
  grouping_flutter/lib/core/shared/color_widget_interface.dart
  grouping_flutter/lib/space/data/repositories/user_repository_impl.dart
  grouping_flutter/lib/space/presentation/view_models/user_page_view_model.dart
  grouping_flutter/lib/space/presentation/views/components/color_card_with_fillings.dart
  grouping_flutter/lib/space/presentation/views/components/setting_title_widget.dart
  grouping_flutter/lib/space/presentation/views/frames/setting_frame.dart
  grouping_flutter/lib/space/presentation/views/pages/user_page_view.dart
  grouping_flutter/lib/space/presentation/views/setting_view.dart
  grouping_flutter/linux/flutter/generated_plugin_registrant.cc
  grouping_flutter/linux/flutter/generated_plugins.cmake
  grouping_flutter/macos/Flutter/GeneratedPluginRegistrant.swift
  grouping_flutter/windows/flutter/generated_plugin_registrant.cc
  grouping_flutter/windows/flutter/generated_plugins.cmake
  grouping_server/database/migrations/0001_initial.py
  grouping_server/database/migrations/0002_activity_image_workspace_user_introduction_and_more.py
  grouping_server/database/models.py
  grouping_server/database/serializers.py
  grouping_server/social_auth/helper_methods.py
  grouping_server/social_auth/serializers.py
  grouping_server/social_auth/views.py
Labels: mission, front-end, back-end

#68 update user setting frame & create workspace dialog view
  .vscode/launch.json
  .vscode/settings.json
  grouping_flutter/lib/app/presentation/components/data_display/title_with_content.dart
  grouping_flutter/lib/app/presentation/providers/theme_provider.dart
  grouping_flutter/lib/app/presentation/views/routes.dart
  grouping_flutter/lib/auth/presentation/views/components/auth_text_form_field.dart
  grouping_flutter/lib/core/theme/color.dart
  grouping_flutter/lib/space/presentation/view_models/user_page_view_model.dart
  grouping_flutter/lib/space/presentation/views/components/color_card_with_fillings.dart
  grouping_flutter/lib/space/presentation/views/components/setting_title_widget.dart
  grouping_flutter/lib/space/presentation/views/components/user_action_button.dart
  grouping_flutter/lib/space/presentation/views/frames/create_workspace_dialog.dart
  grouping_flutter/lib/space/presentation/views/frames/setting_frame.dart
  grouping_flutter/lib/space/presentation/views/frames/user_setting_frame.dart
  grouping_flutter/lib/space/presentation/views/frames/user_space_info_and_navigator_frame.dart
  grouping_flutter/lib/space/presentation/views/message.view.dart
  grouping_flutter/lib/space/presentation/views/pages/user_page_view.dart
  grouping_flutter/lib/space/presentation/views/setting_view.dart
  grouping_flutter/lib/threads/data/repo/get_text_completions_repo_impl.dart
  grouping_flutter/lib/threads/domains/entity/message_entity.dart
  grouping_flutter/lib/threads/domains/repo/gpt_text_completions_repo.dart
  grouping_flutter/lib/threads/domains/usecases/get_gpt_response.dart
  grouping_flutter/lib/threads/presentations/pages/test_page.dart
  grouping_flutter/lib/threads/presentations/viewmodel/thread_view_model.dart
  grouping_flutter/lib/threads/presentations/widgets/chat_action_promt.dart
  grouping_flutter/lib/threads/presentations/widgets/chat_message.dart
  grouping_flutter/lib/threads/presentations/widgets/chat_thread_body.dart
  grouping_flutter/linux/flutter/generated_plugin_registrant.cc
  grouping_flutter/linux/flutter/generated_plugins.cmake
  grouping_flutter/macos/Flutter/GeneratedPluginRegistrant.swift
  grouping_flutter/macos/Podfile.lock
  grouping_flutter/macos/Runner.xcodeproj/project.pbxproj
  grouping_flutter/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  grouping_flutter/windows/flutter/generated_plugin_registrant.cc
  grouping_flutter/windows/flutter/generated_plugins.cmake
Labels: enhancement, front-end

#70 New db get user workspace
  .gitignore
  grouping_server/.gitignore
  grouping_server/database/migrations/0002_remove_user_real_name_remove_user_slogan.py
  grouping_server/database/models.py
  grouping_server/database/serializers.py
  grouping_server/database/viewsets.py
Labels: bug, documentation, enhancement, back-end

#71 add new migration for db
  grouping_server/database/migrations/0003_remove_workspace_is_personal.py
Labels: bug, back-end

#72 auto create workspace when create user
  grouping_server/database/models.py
Labels: enhancement, back-end

#73 feats: added tags add/delete/change functions, finished Setting Frame
  grouping_flutter/lib/app/presentation/components/data_display/title_with_content.dart
  grouping_flutter/lib/auth/presentation/views/pages/login_page_view.dart
  grouping_flutter/lib/auth/presentation/views/pages/register_page_view.dart
  grouping_flutter/lib/space/data/datasources/local_data_source/user_local_data_source.dart
  grouping_flutter/lib/space/data/datasources/remote_data_source/user_remote_data_source.dart
  grouping_flutter/lib/space/data/models/setting_model.dart
  grouping_flutter/lib/space/data/models/user_model.dart
  grouping_flutter/lib/space/data/models/workspace_model.dart
  grouping_flutter/lib/space/data/repositories/user_repository_impl.dart
  grouping_flutter/lib/space/domain/entities/setting_entity.dart
  grouping_flutter/lib/space/domain/entities/space_profile_entity.dart
  grouping_flutter/lib/space/domain/entities/user_entity.dart
  grouping_flutter/lib/space/domain/repositories/user_repository.dart
  grouping_flutter/lib/space/domain/usecases/setting_usecases/get_settings_usecase.dart
  grouping_flutter/lib/space/domain/usecases/setting_usecases/update_setting_usercase.dart
  grouping_flutter/lib/space/domain/usecases/update_current_user.dart
  grouping_flutter/lib/space/presentation/view_models/setting_view_model.dart
  grouping_flutter/lib/space/presentation/view_models/user_page_view_model.dart
  grouping_flutter/lib/space/presentation/views/components/two_info_edit_card.dart
  grouping_flutter/lib/space/presentation/views/frames/create_workspace_dialog.dart
  grouping_flutter/lib/space/presentation/views/frames/user_setting_frame.dart
  grouping_flutter/lib/space/presentation/views/pages/user_page_view.dart
  grouping_server/.env
  grouping_server/social_auth/views.py
Labels: mission, front-end

#78 完成設定頁面，以及頁面導向 UI 小改版
  .vscode/settings.json
  grouping_flutter/lib/app/presentation/components/data_display/title_with_content.dart
  grouping_flutter/lib/app/presentation/views/routes.dart
  grouping_flutter/lib/space/data/datasources/remote_data_source/user_remote_data_source.dart
  grouping_flutter/lib/space/data/models/user_model.dart
  grouping_flutter/lib/space/data/repositories/user_repository_impl.dart
  grouping_flutter/lib/space/domain/entities/user_entity.dart
  grouping_flutter/lib/space/domain/repositories/user_repository.dart
  grouping_flutter/lib/space/presentation/view_models/setting_view_model.dart
  grouping_flutter/lib/space/presentation/view_models/user_page_view_model.dart
  grouping_flutter/lib/space/presentation/views/components/app/dashboard_app_bar.dart
  grouping_flutter/lib/space/presentation/views/components/app/dashboard_drawer.dart
  grouping_flutter/lib/space/presentation/views/components/color_card_with_fillings.dart
  grouping_flutter/lib/space/presentation/views/components/forms/tag_edit_form.dart
  grouping_flutter/lib/space/presentation/views/components/forms/tage_edit_form.dart
  grouping_flutter/lib/space/presentation/views/components/layout/dashboard_layout.dart
  grouping_flutter/lib/space/presentation/views/components/navigated_profile_info_card.dart
  grouping_flutter/lib/space/presentation/views/components/profile_avatar.dart
  grouping_flutter/lib/space/presentation/views/frames/create_workspace_dialog.dart
  grouping_flutter/lib/space/presentation/views/frames/user_setting_frame.dart
  grouping_flutter/lib/space/presentation/views/frames/user_space_info_and_navigator_frame.dart
  grouping_flutter/lib/space/presentation/views/frames/user_space_info_frame.dart
  grouping_flutter/lib/space/presentation/views/pages/user_page_view.dart
  grouping_flutter/lib/space/presentation/views/pages/workspace_page_view.dart
  grouping_flutter/linux/flutter/generated_plugin_registrant.cc
  grouping_flutter/linux/flutter/generated_plugins.cmake
  grouping_flutter/macos/Flutter/GeneratedPluginRegistrant.swift
  grouping_flutter/pubspec.yaml
  grouping_flutter/test/activity_repo_test.dart
  grouping_flutter/test/user_repo_test.dart
  grouping_flutter/windows/flutter/generated_plugin_registrant.cc
  grouping_flutter/windows/flutter/generated_plugins.cmake
Labels: enhancement

#79 UserPage ActivityListFrame
  grouping_flutter/lib/space/data/models/activity_model.dart
  grouping_flutter/lib/space/data/models/event_model.dart
  grouping_flutter/lib/space/data/models/mission_model.dart
  grouping_flutter/lib/space/data/models/mission_state_stage.dart
  grouping_flutter/lib/space/data/models/workspace_model.dart
  grouping_flutter/lib/space/domain/entities/activity_entity.dart
  grouping_flutter/lib/space/domain/entities/event_entity.dart
  grouping_flutter/lib/space/domain/entities/mission_entity.dart
  grouping_flutter/lib/space/presentation/view_models/activity_list_view_model.dart
  grouping_flutter/lib/space/presentation/view_models/event_view_model.dart
  grouping_flutter/lib/space/presentation/view_models/mission_view_model.dart
  grouping_flutter/lib/space/presentation/views/components/layout/activity_layout.dart
  grouping_flutter/lib/space/presentation/views/frames/activity_list_frame.dart
  grouping_flutter/lib/space/presentation/views/pages/user_page_view.dart
  grouping_flutter/pubspec.yaml
Labels: mission, front-end

#84 修正 calendar 以及 activity list
  grouping_flutter/lib/space/presentation/view_models/activity_list_view_model.dart
  grouping_flutter/lib/space/presentation/view_models/setting_view_model.dart
  grouping_flutter/lib/space/presentation/views/components/layout/activity_layout.dart
  grouping_flutter/lib/space/presentation/views/frames/activity_list_frame.dart
Labels: invalid, front-end

#93 DB: change get activity
  grouping_server/database/serializers.py
  grouping_server/database/viewsets.py
Labels: bug, documentation, back-end

#96 DB: serializers reorganize
  grouping_server/database/serializers.py
  grouping_server/database/viewsets.py
  grouping_server/grouping_server/settings.py
Labels: bug, back-end
