Repository quan0715/grouping_application, pull requests merged in 2023-11, with the labels that each got.

#22 Feats: 完成 workspace model 與 user repo file 及其相關測試 + 新增註解
  grouping_flutter/lib/model/auth/account_model.dart
  grouping_flutter/lib/model/auth/register_model.dart
  grouping_flutter/lib/model/photo_model.dart
  grouping_flutter/lib/model/repo/activity_repo.dart
  grouping_flutter/lib/model/repo/patch_enum.dart
  grouping_flutter/lib/model/repo/repo.dart
  grouping_flutter/lib/model/repo/user_repo.dart
  grouping_flutter/lib/model/repo/user_repo_model.dart
  grouping_flutter/lib/model/repo/workspace_repo.dart
  grouping_flutter/lib/model/workspace/editable_card_model.dart
  grouping_flutter/lib/model/workspace/editable_model(undone).dart
  grouping_flutter/lib/model/workspace/event_model.dart
  grouping_flutter/lib/model/workspace/mission_model.dart
  grouping_flutter/lib/model/workspace/workspace_model.dart
  grouping_flutter/test/activity_repo_test.dart
  grouping_flutter/test/repo_test.dart
  grouping_flutter/test/user_repo_test.dart
  grouping_flutter/test/workspace_repo_test.dart
Labels: mission, front-end

#25 Feats: code after cleaning
  grouping_flutter/assets/.env
  grouping_flutter/lib/ViewModel/auth/login_view_model.dart
  grouping_flutter/lib/model/auth/login_model.dart
  grouping_flutter/lib/model/auth/register_model.dart
  grouping_flutter/lib/service/auth/account.dart
  grouping_flutter/lib/service/auth/auth_helpers.dart
  grouping_flutter/lib/service/auth/auth_service.dart
  grouping_flutter/lib/service/auth/github_auth.dart
  grouping_flutter/lib/service/auth/google_auth.dart
  grouping_flutter/lib/service/auth/line_auth.dart
  grouping_flutter/lib/service/auth/mobile_oauth2.dart
  grouping_flutter/lib/service/auth/web_oauth2.dart
  grouping_flutter/linux/flutter/generated_plugin_registrant.cc
  grouping_flutter/linux/flutter/generated_plugins.cmake
  grouping_flutter/macos/Flutter/GeneratedPluginRegistrant.swift
  grouping_flutter/test/login_test.dart
  grouping_flutter/windows/flutter/generated_plugin_registrant.cc
  grouping_flutter/windows/flutter/generated_plugins.cmake
  grouping_server/grouping_server/urls.py
  grouping_server/social_auth/serializers.py
  grouping_server/social_auth/urls.py
  grouping_server/social_auth/views.py
  grouping_server/social_auth/viewsets.py
Labels: enhancement, back-end

#28 fix: change the name of a field in activity in db
  grouping_server/database/models.py
  grouping_server/database/serializers.py
Labels: back-end

#32 message service & some code modify
  grouping_flutter/lib/View/app/helper_page/building.dart
  grouping_flutter/lib/View/app/helper_page/cover_view.dart
  grouping_flutter/lib/View/app/helper_page/page_not_found.dart
  grouping_flutter/lib/View/app/workspace/EditableCard/event_card_view.dart
  grouping_flutter/lib/View/app/workspace/EditableCard/mission_card_view.dart
  grouping_flutter/lib/View/app/workspace/workspace_create_sheet_view.dart
  grouping_flutter/lib/View/app/workspace/workspace_dashboard_page.dart
  grouping_flutter/lib/View/app/workspace/workspace_view.dart
  grouping_flutter/lib/View/components/activity_components/card_display_component.dart
  grouping_flutter/lib/View/components/activity_components/cards_components.dart
  grouping_flutter/lib/View/components/app_log_message_card.dart
  grouping_flutter/lib/View/components/components.dart
  grouping_flutter/lib/View/theme/color.dart
  grouping_flutter/lib/ViewModel/message_service.dart
  grouping_flutter/lib/ViewModel/profile/create_group_view_model.dart
  grouping_flutter/lib/ViewModel/profile/profile_edit_view_model.dart
  grouping_flutter/lib/ViewModel/profile/profile_view_model_lib.dart
  grouping_flutter/lib/ViewModel/profile/qr_view_model.dart
  grouping_flutter/lib/ViewModel/workspace/editable_card_view_model.dart
  grouping_flutter/lib/ViewModel/workspace/event_view_model.dart
  grouping_flutter/lib/ViewModel/workspace/mission_view_model.dart
  grouping_flutter/lib/ViewModel/workspace/workspace_dashboard_view_model.dart
  grouping_flutter/lib/ViewModel/workspace/workspace_view_model.dart
  grouping_flutter/lib/ViewModel/workspace/workspace_view_model_lib.dart
  grouping_flutter/lib/main.dart
  grouping_flutter/lib/model/auth/login_model.dart
  grouping_flutter/lib/model/card_ui_model.dart
  grouping_flutter/lib/model/workspace/message_model.dart
Labels: enhancement, front-end

#35 Feats: Set Up Token Auths and Permissions
  grouping_flutter/lib/View/app/auth/pages/login_page_view.dart
  grouping_flutter/lib/main.dart
  grouping_flutter/lib/service/auth/account.dart
  grouping_flutter/lib/service/auth/auth_helpers.dart
  grouping_flutter/lib/service/auth/github_auth.dart
  grouping_flutter/lib/service/auth/google_auth.dart
  grouping_flutter/lib/service/auth/line_auth.dart
  grouping_flutter/lib/service/auth/mobile_oauth2.dart
  grouping_flutter/lib/service/auth/web_oauth2.dart
  grouping_flutter/linux/flutter/generated_plugin_registrant.cc
  grouping_flutter/linux/flutter/generated_plugins.cmake
  grouping_flutter/macos/Flutter/GeneratedPluginRegistrant.swift
  grouping_flutter/windows/flutter/generated_plugin_registrant.cc
  grouping_flutter/windows/flutter/generated_plugins.cmake
  grouping_server/database/migrations/0002_remove_activity_childs_activity_children.py
  grouping_server/database/models.py
  grouping_server/grouping_server/settings.py
  grouping_server/grouping_server/urls.py
  grouping_server/social_auth/authentication.py
  grouping_server/social_auth/config.py
  grouping_server/social_auth/github_and_line.py
  grouping_server/social_auth/google.py
  grouping_server/social_auth/helper_methods.py
  grouping_server/social_auth/register.py
  grouping_server/social_auth/serializers.py
  grouping_server/social_auth/views.py
Labels: mission, back-end

#33 新增前端儀表板、活動 GUI
  grouping_flutter/android/build.gradle
  grouping_flutter/lib/View/app/workspace/activity_view.dart
  grouping_flutter/lib/View/app/workspace/dashboard_view.dart
  grouping_flutter/lib/View/app/workspace/message.view.dart
  grouping_flutter/lib/View/app/workspace/setting_view.dart
  grouping_flutter/lib/View/app/workspace/workspace_view.dart
  grouping_flutter/lib/View/repo_view.dart
  grouping_flutter/lib/View/shared/components/components.dart
  grouping_flutter/lib/View/shared/components/workspace_chip.dart
  grouping_flutter/lib/ViewModel/workspace/event_view_model.dart
  grouping_flutter/lib/ViewModel/workspace/workspace_view_model.dart
  grouping_flutter/lib/main.dart
  grouping_flutter/lib/model/repo/activity_repo.dart
  grouping_flutter/lib/model/workspace/editable_card_model.dart
  grouping_flutter/lib/model/workspace/event_model.dart
  grouping_flutter/lib/model/workspace/mission_model.dart
  grouping_flutter/linux/flutter/generated_plugin_registrant.cc
  grouping_flutter/linux/flutter/generated_plugins.cmake
  grouping_flutter/macos/Flutter/GeneratedPluginRegistrant.swift
  grouping_flutter/test/activity_repo_test.dart
  grouping_flutter/test/login_test.dart
  grouping_flutter/windows/flutter/generated_plugin_registrant.cc
  grouping_flutter/windows/flutter/generated_plugins.cmake
Labels: mission, front-end

#42 Add unit test for database
  grouping_server/database/migrations/0003_alter_user_account_alter_user_password_and_more.py
  grouping_server/database/models.py
  grouping_server/database/tests.py
Labels: mission, back-end

#44 drawer/app bar
  grouping_flutter/lib/app/presentation/views/routes.dart
  grouping_flutter/lib/core/shared/color_widget_interface.dart
  grouping_flutter/lib/dashboard/data/models/account_model.dart
  grouping_flutter/lib/dashboard/domain/entities/space_profile_entity.dart
  grouping_flutter/lib/dashboard/domain/entities/user_entity.dart
  grouping_flutter/lib/dashboard/domain/entities/user_profile_entity.dart
  grouping_flutter/lib/dashboard/domain/usecases/get_current_user_usecase.dart
  grouping_flutter/lib/dashboard/presentation/view_models/user_page_view_model.dart
  grouping_flutter/lib/dashboard/presentation/views/components/color_card_widget.dart
  grouping_flutter/lib/dashboard/presentation/views/components/dashboard_app_bar.dart
  grouping_flutter/lib/dashboard/presentation/views/components/dashboard_drawer.dart
  grouping_flutter/lib/dashboard/presentation/views/components/drawer_navigation_card.dart
  grouping_flutter/lib/dashboard/presentation/views/components/mobile_app_bar.dart
  grouping_flutter/lib/dashboard/presentation/views/components/mobile_bottom_navigation_bar.dart
  grouping_flutter/lib/dashboard/presentation/views/components/profile_avatar.dart
  grouping_flutter/lib/dashboard/presentation/views/pages/user_page_view.dart
  grouping_flutter/lib/dashboard/presentation/views/user_page_view.dart
  grouping_flutter/lib/main.dart
Labels: enhancement, mission, front-end

#46 Change Token Return Format & Move showWindow Func Into View
  grouping_flutter/lib/auth/presentation/view_models/login_view_model.dart
  grouping_flutter/lib/auth/presentation/views/pages/login_page_view.dart
  grouping_flutter/lib/auth/utils/auth_helpers.dart
  grouping_flutter/lib/auth/utils/oauth_base_service.dart
  grouping_flutter/lib/core/config/config.dart
  grouping_flutter/linux/flutter/generated_plugin_registrant.cc
  grouping_flutter/linux/flutter/generated_plugins.cmake
  grouping_flutter/macos/Flutter/GeneratedPluginRegistrant.swift
  grouping_flutter/test/login_test.dart
  grouping_flutter/windows/flutter/generated_plugin_registrant.cc
  grouping_flutter/windows/flutter/generated_plugins.cmake
  grouping_server/database/migrations/0004_alter_user_introduction_alter_user_photo.py
  grouping_server/grouping_server/settings.py
  grouping_server/social_auth/config.py
  grouping_server/social_auth/google.py
  grouping_server/social_auth/helper_methods.py
  grouping_server/social_auth/register.py
  grouping_server/social_auth/serializers.py
  grouping_server/social_auth/urls.py
  grouping_server/social_auth/views.py
  grouping_server/social_auth/viewsets.py
Labels: enhancement, mission, front-end, back-end

#53 Fix database
  grouping_server/database/migrations/0002_remove_activity_childs_activity_children.py
  grouping_server/database/migrations/0002_rename_childs_activity_children_and_more.py
  grouping_server/database/migrations/0004_alter_user_introduction_alter_user_photo.py
  grouping_server/database/models.py
  grouping_server/database/serializers.py
  grouping_server/server_test.py
Labels: bug, back-end

#54 Change "data" to "image_uri"
  grouping_server/database/serializers.py
Labels: enhancement, back-end
