Repository quan0715/grouping_application, pull requests merged in 2023-10, with the labels that each got.

#1 readme
  README.md
Labels: good first issue

#9 feat: readme update
  README.md
Labels: good first issue

#10 Feats: add platform view, oauth func context param
  grouping_flutter/lib/View/app/auth/auth_view.dart
  grouping_flutter/lib/View/app/auth/web_login_view.dart
  grouping_flutter/lib/View/app/auth/web_sign_in_view.dart
  grouping_flutter/lib/ViewModel/auth/login_view_model.dart
  grouping_flutter/lib/config/config.dart
  grouping_flutter/lib/main.dart
  grouping_flutter/lib/model/auth/login_model.dart
  grouping_flutter/lib/service/auth/auth_service.dart
  grouping_flutter/lib/service/auth/github_auth.dart
  grouping_flutter/lib/service/auth/google_auth.dart
  grouping_flutter/lib/service/auth/line_auth.dart
  grouping_flutter/lib/service/auth/oauth2_mobile.dart
  grouping_flutter/lib/service/auth/oauth2_web.dart
  grouping_flutter/linux/flutter/generated_plugin_registrant.cc
  grouping_flutter/linux/flutter/generated_plugins.cmake
  grouping_flutter/macos/Flutter/GeneratedPluginRegistrant.swift
  grouping_flutter/pubspec.yaml
  grouping_flutter/windows/flutter/generated_plugin_registrant.cc
  grouping_flutter/windows/flutter/generated_plugins.cmake
  grouping_server/requirements.txt
  grouping_server/social_auth/config.py
  grouping_server/social_auth/serializers.py
  grouping_server/social_auth/urls.py
  grouping_server/social_auth/views.py
Labels: enhancement, mission, back-end

#16 Shared Widget 新增 & AuthInterface 新增
  grouping_flutter/ios/Podfile.lock
  grouping_flutter/lib/View/app/app_view.dart
  grouping_flutter/lib/View/app/auth/auth_view.dart
  grouping_flutter/lib/View/app/auth/components/action_text_button.dart
  grouping_flutter/lib/View/app/auth/components/auth_layout.dart
  grouping_flutter/lib/View/app/auth/components/auth_text_form_field.dart
  grouping_flutter/lib/View/app/auth/components/third_party_login_button.dart
  grouping_flutter/lib/View/app/auth/mobile_oauth_page.dart
  grouping_flutter/lib/View/app/auth/pages/cover_page_view.dart
  grouping_flutter/lib/View/app/auth/pages/login_page_view.dart
  grouping_flutter/lib/View/app/auth/pages/register_page_view.dart
  grouping_flutter/lib/View/app/auth/pages/welcome_message_page_view.dart
  grouping_flutter/lib/View/app/auth/sign_up_view.dart
  grouping_flutter/lib/View/app/auth/web_login_view.dart
  grouping_flutter/lib/View/app/auth/web_sign_in_view.dart
  grouping_flutter/lib/View/app/auth/welcome_message_view.dart
  grouping_flutter/lib/View/app/helper_page/building.dart
  grouping_flutter/lib/View/app/helper_page/page_not_found.dart
  grouping_flutter/lib/View/components/app_elevated_button.dart
  grouping_flutter/lib/View/components/auth_view/auth_view_components_lib.dart
  grouping_flutter/lib/View/components/auth_view/headline_with_content.dart
  grouping_flutter/lib/View/components/auth_view/input_box.dart
  grouping_flutter/lib/View/components/auth_view/navigation_toggle_bar.dart
  grouping_flutter/lib/View/components/button/auth_button.dart
  grouping_flutter/lib/View/components/button/overview_choice_button.dart
  grouping_flutter/lib/View/components/sing_up_page_template.dart
  grouping_flutter/lib/View/components/title_with_content.dart
  grouping_flutter/lib/View/theme/theme_manager.dart
  grouping_flutter/lib/ViewModel/application1/application1_view_model.dart
  grouping_flutter/lib/ViewModel/auth/login_view_model.dart
  grouping_flutter/lib/ViewModel/auth/register_view_model.dart
  grouping_flutter/lib/config/assets.dart
  grouping_flutter/lib/main.dart
  grouping_flutter/lib/model/auth/login_model.dart
  grouping_flutter/lib/model/theme_model.dart
  grouping_flutter/linux/flutter/generated_plugin_registrant.cc
  grouping_flutter/linux/flutter/generated_plugins.cmake
  grouping_flutter/macos/Flutter/GeneratedPluginRegistrant.swift
  grouping_flutter/pubspec.yaml
  grouping_flutter/windows/flutter/generated_plugin_registrant.cc
  grouping_flutter/windows/flutter/generated_plugins.cmake
Labels: enhancement, mission, front-end

#18 Fix multiple bugs and add some little convenience feature in backend.
  grouping_server/.gitignore
  grouping_server/database/models.py
  grouping_server/database/serializers.py
  grouping_server/database/viewsets.py
  grouping_server/grouping_server/settings.py
Labels: bug, back-end

#12 Feats: 完成 activity repo model 的基本接收
  grouping_flutter/lib/model/auth/account_model.dart
  grouping_flutter/lib/model/repo/patch_enum.dart
  grouping_flutter/lib/model/repo/repo.dart
  grouping_flutter/lib/model/repo/user_repo_model.dart
  grouping_flutter/lib/model/workspace/activity.dart
  grouping_flutter/lib/model/workspace/data_model.dart
  grouping_flutter/lib/model/workspace/editable_card_model.dart
  grouping_flutter/lib/model/workspace/event_model.dart
  grouping_flutter/lib/model/workspace/mission_model.dart
  grouping_flutter/lib/model/workspace/mission_state_model.dart
  grouping_flutter/pubspec.yaml
  grouping_flutter/test/repo_test.dart
Labels: mission, front-end

#20 Feats: enable line login with redirect change
  grouping_flutter/lib/View/app/auth/auth_view.dart
  grouping_flutter/lib/View/app/auth/pages/login_page_view.dart
  grouping_flutter/lib/ViewModel/auth/login_view_model.dart
  grouping_flutter/lib/config/config.dart
  grouping_flutter/lib/main.dart
  grouping_flutter/lib/model/auth/login_model.dart
  grouping_flutter/lib/service/auth/auth_helpers.dart
  grouping_flutter/lib/service/auth/auth_service.dart
  grouping_flutter/lib/service/auth/github_auth.dart
  grouping_flutter/lib/service/auth/google_auth.dart
  grouping_flutter/lib/service/auth/line_auth.dart
  grouping_flutter/lib/service/auth/mobile_oauth2.dart
  grouping_flutter/lib/service/auth/oauth2_mobile.dart
  grouping_flutter/lib/service/auth/oauth2_web.dart
  grouping_flutter/lib/service/auth/web_oauth2.dart
  grouping_flutter/linux/flutter/generated_plugin_registrant.cc
  grouping_flutter/linux/flutter/generated_plugins.cmake
  grouping_flutter/macos/Flutter/GeneratedPluginRegistrant.swift
  grouping_flutter/windows/flutter/generated_plugin_registrant.cc
  grouping_flutter/windows/flutter/generated_plugins.cmake
  grouping_server/social_auth/config.py
  grouping_server/social_auth/github_and_line.py
  grouping_server/social_auth/google.py
  grouping_server/social_auth/helper_methods.py
  grouping_server/social_auth/serializers.py
  grouping_server/social_auth/urls.py
  grouping_server/social_auth/views.py
Labels: enhancement, mission, back-end
