Repository quan0715/grouping_application, pull requests merged in 2024-01, with the labels that each got.

#101 Finished the UI of Activity Display
  grouping_flutter/lib/auth/data/datasources/auth_local_data_source.dart
  grouping_flutter/lib/auth/data/datasources/auth_remote_data_source.dart
  grouping_flutter/lib/auth/data/repositories/auth_repository_impl.dart
  grouping_flutter/lib/auth/domain/entities/code_entity.dart
  grouping_flutter/lib/auth/domain/repositories/auth_login_repositories.dart
  grouping_flutter/lib/auth/domain/usecases/edxchange_token_with_code.dart
  grouping_flutter/lib/auth/presentation/view_models/login_view_model.dart
  grouping_flutter/lib/auth/presentation/views/pages/login_page_view.dart
  grouping_flutter/lib/auth/utils/oauth_base_service.dart
  grouping_flutter/lib/space/data/datasources/remote_data_source/workspace_remote_data_source.dart
  grouping_flutter/lib/space/presentation/view_models/activity_list_view_model.dart
  grouping_flutter/lib/space/presentation/views/components/layout/time_display_with_pressable_body.dart
  grouping_flutter/lib/space/presentation/views/frames/activity_frame.dart
  grouping_flutter/pubspec.yaml
  grouping_server/social_auth/views.py
Labels: enhancement, mission, front-end

#98 修正 Model, Entity 的 logic error
  grouping_flutter/lib/core/data/models/mission_state_model.dart
  grouping_flutter/lib/core/data/models/mission_state_stage.dart
  grouping_flutter/lib/core/util/base_entity.dart
  grouping_flutter/lib/core/util/base_model.dart
  grouping_flutter/lib/core/util/data_mapper.dart
  grouping_flutter/lib/space/data/datasources/remote_data_source/activity_remote_data_source.dart
  grouping_flutter/lib/space/data/datasources/remote_data_source/user_remote_data_source.dart
  grouping_flutter/lib/space/data/datasources/remote_data_source/workspace_remote_data_source.dart
  grouping_flutter/lib/space/data/models/activity_model.dart
  grouping_flutter/lib/space/data/models/event_model.dart
  grouping_flutter/lib/space/data/models/mission_model.dart
  grouping_flutter/lib/space/data/models/mission_state_model.dart
  grouping_flutter/lib/space/data/models/user_model.dart
  grouping_flutter/lib/space/data/models/workspace_model.dart
  grouping_flutter/lib/space/data/models/workspace_model_lib.dart
  grouping_flutter/lib/space/data/repositories/activity_repository_impl.dart
  grouping_flutter/lib/space/data/repositories/user_repository_impl.dart
  grouping_flutter/lib/space/data/repositories/workspace_repository_impl.dart
  grouping_flutter/lib/space/domain/entities/activity_entity.dart
  grouping_flutter/lib/space/domain/entities/event_entity.dart
  grouping_flutter/lib/space/domain/entities/mission_entity.dart
  grouping_flutter/lib/space/domain/entities/user_entity.dart
  grouping_flutter/lib/space/domain/entities/workspace_entity.dart
  grouping_flutter/lib/space/domain/usecases/activity_usecases/create_event_usecase.dart
  grouping_flutter/lib/space/domain/usecases/activity_usecases/create_mission_usecase.dart
  grouping_flutter/lib/space/domain/usecases/activity_usecases/get_event_usecase.dart
  grouping_flutter/lib/space/domain/usecases/activity_usecases/get_mission_usecase.dart
  grouping_flutter/lib/space/domain/usecases/activity_usecases/update_event_usecase.dart
  grouping_flutter/lib/space/domain/usecases/activity_usecases/update_mission_usecase.dart
  grouping_flutter/lib/space/domain/usecases/workspace_usecases/join_worksapcee_usecase.dart
  grouping_flutter/lib/space/presentation/view_models/activity_list_view_model.dart
  grouping_flutter/lib/space/presentation/view_models/event_view_model.dart
  grouping_flutter/lib/space/presentation/view_models/mission_view_model.dart
  grouping_flutter/lib/space/presentation/view_models/setting_view_model.dart
  grouping_flutter/lib/space/presentation/view_models/space_view_model.dart
  grouping_flutter/lib/space/presentation/views/components/layout/activity_layout.dart
  grouping_flutter/lib/space/presentation/views/frames/activity_list_frame.dart
  grouping_flutter/test/workspace_repo_test.dart
Labels: enhancement, invalid, front-end

#106 重新設計 Mission State API 以及 State 相關檔案
  grouping_flutter/lib/core/data/models/mission_state_model.dart
  grouping_flutter/lib/core/data/models/mission_state_stage.dart
  grouping_flutter/lib/core/data/models/nest_workspace.dart
  grouping_flutter/lib/core/util/base_usecase.dart
  grouping_flutter/lib/space/data/datasources/local_data_source/state_local_data_source.dart
  grouping_flutter/lib/space/data/datasources/remote_data_source/activity_remote_data_source.dart
  grouping_flutter/lib/space/data/datasources/remote_data_source/state_remote_data_source.dart
  grouping_flutter/lib/space/data/datasources/remote_data_source/workspace_remote_data_source.dart
  grouping_flutter/lib/space/data/models/activity_model.dart
  grouping_flutter/lib/space/data/models/event_model.dart
  grouping_flutter/lib/space/data/models/mission_model.dart
  grouping_flutter/lib/space/data/models/user_model.dart
  grouping_flutter/lib/space/data/models/workspace_model.dart
  grouping_flutter/lib/space/data/repositories/state_repository_impl.dart
  grouping_flutter/lib/space/domain/entities/activity_entity.dart
  grouping_flutter/lib/space/domain/entities/event_entity.dart
  grouping_flutter/lib/space/domain/entities/mission_entity.dart
  grouping_flutter/lib/space/domain/entities/user_entity.dart
  grouping_flutter/lib/space/domain/entities/workspace_entity.dart
  grouping_flutter/lib/space/domain/repositories/state_repository.dart
  grouping_flutter/lib/space/domain/usecases/activity_usecases/activity_usecase_lib.dart
  grouping_flutter/lib/space/domain/usecases/activity_usecases/create_event_usecase.dart
  grouping_flutter/lib/space/domain/usecases/activity_usecases/create_mission_usecase.dart
  grouping_flutter/lib/space/domain/usecases/activity_usecases/delete_activity_usecase.dart
  grouping_flutter/lib/space/domain/usecases/activity_usecases/get_event_usecase.dart
  grouping_flutter/lib/space/domain/usecases/activity_usecases/get_mission_usecase.dart
  grouping_flutter/lib/space/domain/usecases/activity_usecases/update_event_usecase.dart
  grouping_flutter/lib/space/domain/usecases/activity_usecases/update_mission_usecase.dart
  grouping_flutter/lib/space/domain/usecases/state_usecases/create_state_usecase.dart
  grouping_flutter/lib/space/domain/usecases/state_usecases/delete_state_usecase.dart
  grouping_flutter/lib/space/domain/usecases/state_usecases/get_state_usecase.dart
  grouping_flutter/lib/space/domain/usecases/state_usecases/update_state_usecase.dart
  grouping_flutter/lib/space/presentation/view_models/activity_list_view_model.dart
  grouping_flutter/lib/space/presentation/views/components/layout/activity_layout.dart
  grouping_flutter/lib/space/presentation/views/frames/activity_frame.dart
  grouping_flutter/test/activity_repo_test.dart
Labels: mission, front-end
